version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
        DB_CONNECTION: pgsql
        DB_HOST: db_server
        DB_PORT: 3306
        DB_DATABASE: chat_app_sd
        DB_USERNAME: fm
        DB_PASSWORD: '@fm21@'

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: db_server
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
