# version: "3.9"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile-laravel
    ports:
      - "8000:8000"
    volumes:
      - ./chat-app-sd-app:/var/www/html
    container_name: chat-app
    depends_on:
      - redis
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: chat_app_sd
      DB_USERNAME: fm
      DB_PASSWORD: "@fm21@"

  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"
    volumes:
      - ./websocket-server:/app
    container_name: websocker-server
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_app_sd
      MYSQL_USER: fm
      MYSQL_PASSWORD: "@fm21@"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: